### ISSUE TITLE
Not debugging 

### ISSUE THREAD

**Issue by swarupbhc** [mikkyboy2005/smakos#1]

**Comment by mikkyboy2005** [comment]
What OS are you debugging for?

**Comment by mikkyboy2005** [comment]
What OS are you debugging for?

**Comment by MikkyBoy357** [comment]
For what OS does debug not work?

**Comment by swarupbhc** [comment]
from Linux to android

**Comment by MikkyBoy357** [comment]
It works from mac to android on Android Studio. 
There might be a problem with your IDE (if you are using VS Code).

**Comment by MikkyBoy357** [comment]
perhaps your android version is too low for the app.

Run `flutter clean` in the root project and try again.
